spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ejemploLogin
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: secret
  expiration: 86400000  #24 horas
  